package com.conclusion.transparencyPortalService;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

import java.io.FileWriter;
import java.io.IOException;
import java.util.Random;

@SpringBootTest
class TransparencyPortalServiceApplicationTests {
    private static final int LIST_SIZE = 100000;

    @Test
    void dataGenerator() throws JSONException {
        JSONArray medicalSupplies = new JSONArray();

        for (int i = 0; i < LIST_SIZE; i++) {
            System.out.println("Generating item: " + i);
            JSONObject supply = generateMedicalSupply();
            medicalSupplies.put(supply);
        }

        try (FileWriter file = new FileWriter("medical_supplies.json")) {
            file.write(medicalSupplies.toString(2));
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public static JSONObject generateMedicalSupply() throws JSONException {
        String[] supplyNames = {
                "Painkillers",
                "Antibiotics",
                "Bandages",
                "Surgical Gloves",
                "IV Fluids",
                "Gauze",
                "Scalpels",
                "X-ray Machines",
                "Stethoscopes",
                "Wheelchairs",
                "Crutches",
                "Orthopedic Implants",
                "Anesthetics",
                "Syringes",
                "First Aid Kits",
                "Medical Masks",
                "Ventilators",
                "Defibrillators",
                "MRI Machines",
                "Blood Pressure Monitors",
                "EKG Machines",
                "Medical Scissors",
                "Thermometers",
                "Oxygen Concentrators",
                "Hospital Beds",
                "Laboratory Equipment",
                "Ambulance Stretchers",
                "Dental Instruments",
                "Medical Charts",
                "Pharmaceuticals",
                "Ultrasound Machines",
                "Dialysis Machines",
                "Blood Bags",
                "Oxygen Tanks",
                "Catheters",
                "ECG Electrodes",
                "Neonatal Incubators",
                "Prosthetics",
                "Wheelchair Ramps",
                "Hearing Aids",
                "Diabetic Supplies",
                "Respirators",
                "Tourniquets",
                "Pulse Oximeters",
                "Nebulizers",
                "Patient Lifts",
                "Mobility Scooters",
                "Walking Canes",
                "Medical Pumps",
                "Intravenous Poles",
                "Patient Monitors",
                "Ophthalmic Instruments",
                "Medical Gloves",
                "Wound Dressings",
                "Nasal Cannulas",
                "Blood Glucose Meters",
                "Orthopedic Braces",
                "Surgical Drapes",
                "Dental X-ray Machines",
                "Nursing Uniforms",
                "Orthodontic Appliances",
                "Inhalers",
                "Cast Padding",
                "Medical Scales",
                "Kidney Dish",
                "Stethoscope Covers",
                "Catheter Bags",
                "Medical Tapes",
                "Adhesive Bandages",
                "Foley Catheters",
                "Bone Plates",
                "Tissue Forceps",
                "Electrocardiogram Paper",
                "Orthopedic Shoes",
                "Medical Forceps",
                "Nasogastric Tubes",
                "Artificial Airways",
                "Surgical Masks",
                "Ostomy Bags",
                "Feeding Tubes",
                "Nurse Call Systems",
                "Medical Waste Bins",
                "Medical Needles",
                "Surgical Drills",
                "Dental Chairs",
                "Surgical Gowns",
                "Cervical Collars",
                "Blood Lancets",
                "Wrist Braces",
                "Anesthesia Machines",
                "Dental Fillings",
                "Disposable Gloves",
                "Orthopedic Casts",
                "Bedpans",
                "Compression Stockings",
                "Tongue Depressors",
                "Oxygen Masks",
                "Medical Carts",
                "Respiratory Masks",
                "Medical Gowns",
                "Nurse Caps",
                "Surgical Staplers",
                "Pulse Lavage Systems",
                "Orthopedic Screws",
                "Kidney Trays",
                "Surgical Needles",
                "Catheter Securement Devices",
                "Sterile Swabs",
                "Medical Drains",
                "Wound Irrigation Systems"
        };
        String[] fromPlaces = {
                "Pharmacy A",
                "Pharmacy B",
                "Medical Supplier Z",
                "Hospital Pharmacy",
                "Clinic Supplies",
                "Medical Supply Company X",
                "Healthcare Warehouse",
                "Wholesale Pharmacy",
                "Manufacturer Direct",
                "Local Distributor",
                "Online Retailer",
                "Regional Medical Center",
                "Specialty Pharmacy",
                "Veterinary Clinic Supplies",
                "Government Procurement",
                "International Importer",
                "Pharmaceutical Manufacturer",
                "Medical Equipment Wholesaler",
                "Home Healthcare Provider",
                "Hospice Supplier",
                "Rehabilitation Center Store",
                "Surgical Instrument Supplier",
                "Long-Term Care Facility",
                "Dental Supply Store",
                "Orthopedic Equipment Supplier",
                "Optical Supplies Distributor",
                "Pediatric Medical Supplies",
                "Durable Medical Equipment Store",
                "Assisted Living Facility",
                "Maternity Clinic Supplies",
                "Diagnostic Imaging Center",
                "Cardiology Equipment Supplier",
                "Respiratory Therapy Supplies",
                "Chiropractic Equipment Store",
                "Physical Therapy Clinic Supplies",
                "Medical Laboratory",
                "Radiology Center",
                "Denture Laboratory",
                "Blood Bank",
                "Medical Research Institute",
                "Plastic Surgery Clinic Supplies",
                "Hearing Aid Center",
                "Ophthalmology Equipment Supplier",
                "Prosthetics and Orthotics Store",
                "Veterinary Laboratory",
                "Phlebotomy Supplies Vendor",
                "Medical Records Department",
                "Biotechnology Company",
                "Rehabilitation Equipment Supplier",
                "Herbal Medicine Store",
                "Medical Equipment Leasing",
                "Dental Laboratory",
                "Pain Management Clinic Supplies",
                "Urgent Care Center Store",
                "Reproductive Health Clinic Supplies",
                "Allergy Testing Center",
                "Orthopedic Bracing Store",
                "Radiation Oncology Center",
                "Home Infusion Pharmacy",
                "Hearing Testing Center",
                "Sleep Center Supplies",
                "Respiratory Care Clinic Supplies",
                "Podiatry Supplies Vendor",
                "Veterinary Diagnostic Imaging Center",
                "Dental Implant Center",
                "Fertility Clinic Supplies",
                "Home Health Supplies",
                "Medical Spa",
                "Orthodontic Lab",
                "Nutrition Supplement Store",
                "Medical Aesthetics Center",
                "Pediatric Dental Supplies",
                "Vein Clinic Supplies",
                "Medical Oxygen Supplier",
                "Surgical Supply Store",
                "Imaging Equipment Rental",
                "Nursing Home Pharmacy",
                "Holistic Medicine Store",
                "Telemedicine Equipment Supplier",
                "Medical Marijuana Dispensary",
                "Dental Equipment Leasing",
                "Veterinary Rehabilitation Center",
                "Weight Loss Clinic Supplies"
        };
        String[] toPlaces = {
                "Hospital X",
                "Clinic Y",
                "Emergency Room",
                "Surgical Ward",
                "Patient Room",
                "Intensive Care Unit",
                "Labor and Delivery Room",
                "Operating Room",
                "Recovery Room",
                "Radiology Department",
                "Pharmacy Department",
                "Laboratory",
                "Outpatient Clinic",
                "Maternity Ward",
                "Pediatric Ward",
                "Neonatal Intensive Care Unit",
                "Cardiac Care Unit",
                "Burn Unit",
                "Oncology Ward",
                "Orthopedic Ward",
                "Psychiatric Ward",
                "Physical Therapy Department",
                "Dental Clinic",
                "Ophthalmology Clinic",
                "ENT (Ear, Nose, Throat) Clinic",
                "Gynecology Clinic",
                "Orthodontics Department",
                "Chiropractic Clinic",
                "Pain Management Clinic",
                "Sports Medicine Clinic",
                "Rehabilitation Center",
                "Imaging Center",
                "Blood Bank",
                "Medical Research Facility",
                "Phlebotomy Lab",
                "Emergency Medical Services (EMS)",
                "Long-Term Care Facility",
                "Hospice Care Facility",
                "Dental Laboratory",
                "Prosthetics and Orthotics Center",
                "Veterinary Clinic",
                "Animal Hospital",
                "Home Healthcare",
                "Ambulatory Surgery Center",
                "Dialysis Center",
                "Dental Implant Center",
                "Fertility Clinic",
                "Plastic Surgery Center",
                "Alternative Medicine Clinic",
                "Audiology Clinic",
                "Sleep Clinic",
                "Urgent Care Center",
                "Physical Fitness Center",
                "Nutrition and Wellness Center",
                "Medical Spa",
                "Chiropractic Wellness Center",
                "Holistic Healing Center",
                "Reproductive Health Center",
                "Weight Loss Clinic",
                "Acupuncture Clinic",
                "Telemedicine Consultation",
                "Medical Marijuana Dispensary",
                "Community Health Center",
                "School Health Clinic",
                "Corporate Health Center",
                "Mobile Clinic",
                "Military Medical Unit",
                "Nursing Home",
                "Assisted Living Facility",
                "Veterans Affairs (VA) Hospital"
        };
        String[] updateBy = {"Nurse Jane",
                "Doctor Smith",
                "Paramedic Sam",
                "Doctor Vinicius Primao",
                "Paramedic Julia Primao",
                "Nurse Carla Primao",
                "Doctor Sophia Primao"};
        String[] destinies = {
                "Patient Room 101",
                "Patient Room 205",
                "Treatment Area 3",
                "Surgical Suite 2",
                "Recovery Room",
                "Pediatric Ward",
                "Neonatal ICU",
                "Maternity Ward",
                "Operating Room 1",
                "Operating Room 2",
                "ICU - Intensive Care Unit",
                "Radiology Department",
                "Laboratory",
                "Emergency Room 1",
                "Emergency Room 2",
                "Pharmacy",
                "Outpatient Clinic",
                "Dental Clinic",
                "Orthopedic Ward",
                "Oncology Ward",
                "Cardiac Care Unit",
                "Burn Unit",
                "Psychiatric Ward",
                "Physical Therapy Department",
                "ENT Clinic",
                "Ophthalmology Clinic",
                "Gynecology Clinic",
                "Pediatric Clinic",
                "Orthodontics Department",
                "Chiropractic Clinic",
                "Pain Management Clinic",
                "Sports Medicine Clinic",
                "Rehabilitation Center",
                "Imaging Center",
                "Blood Bank",
                "Medical Research Facility",
                "Veterinary Clinic",
                "Animal Hospital",
                "Home Healthcare",
                "Ambulatory Surgery Center",
                "Dialysis Center",
                "Dental Implant Center",
                "Fertility Clinic",
                "Plastic Surgery Center",
                "Alternative Medicine Center",
                "Audiology Clinic",
                "Sleep Clinic",
                "Urgent Care Center",
                "Physical Fitness Center",
                "Nutrition and Wellness Center",
                "Medical Spa",
                "Chiropractic Wellness Center",
                "Holistic Healing Center",
                "Reproductive Health Center",
                "Weight Loss Clinic",
                "Acupuncture Clinic",
                "Telemedicine Consultation",
                "Medical Marijuana Dispensary",
                "Community Health Center",
                "School Health Clinic",
                "Corporate Health Center",
                "Mobile Clinic",
                "Military Medical Unit",
                "Nursing Home",
                "Assisted Living Facility",
                "Veterans Affairs (VA) Hospital"
        };
        boolean arrived = new Random().nextBoolean();

        JSONObject supply = new JSONObject();
        supply.put("supplyName", supplyNames[new Random().nextInt(supplyNames.length)]);
        supply.put("supplyValue", Math.round((5.0 + (Math.random() * (100.0 - 5.0))) * 100.0) / 100.0);
        supply.put("fromPlace", fromPlaces[new Random().nextInt(fromPlaces.length)]);
        supply.put("toPlace", toPlaces[new Random().nextInt(toPlaces.length)]);
        supply.put("updateBy", updateBy[new Random().nextInt(updateBy.length)]);
        supply.put("destiny", destinies[new Random().nextInt(destinies.length)]);
        supply.put("arrived", arrived);

        return supply;
    }

}
